### ISSUE TITLE
Irregardless Grammar Project

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#106]
# Clueless Co-Worker Email

The goal of the project is to create either a humorous email or passage where a person makes a series of common grammar mistakes. 

Background: We’re looking to build a relationship with DonorsChoose.org. The founder of it, Charles Best, has created a side project called Irregardless.ly, which provides writing types. This site was built out of his frustration with the poor writing he saw at DonorsChoose. To connect with Charles (as well as their board members and others), I would like to put together a humorous “joke” email that contains the eight grammatical errors listed above.

The theme of the email should be something like “Clueless Co-Worker”, and it should have some sort of conflict in it - for example, it could be about a co-worker trying to plan an office party, or it could be about something completely unrelated. It doesn’t have to be an office related email either, the only hard requirement is that it should use these words. 

Very Unique -> Unique

Literally -> Figuratively 

Alot -> a lot

Pour Over -> pore over

Irregardless -> Regardless

Baited Breath -> Bated Breath

Myself -> Me (e.g. when people write, Tom and myself went to the zoo). 

Alright -> All right. 

Doggie Dog World -> Dog Eat Dog World

**Comment by elliotmandel** [comment]
Email created by the esteemed interns!
