### ISSUE TITLE
Problems with particular questions

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Quill-Grammar#109]
![screen shot 2015-07-28 at 11 21 33 am](https://cloud.githubusercontent.com/assets/1789723/8935449/d89596c4-351a-11e5-82ee-7444107a391a.png)

**Comment by marcellosachs** [comment]
https://staging.quill.org/activities/156?session=1680761

**Comment by marcellosachs** [comment]
had another problem with this question : 
https://staging.quill.org/activities/155?session=1680782
(logged in as Test1_c1.s1.s1@sweet-stamp)
![screen shot 2015-07-28 at 11 50 55 am](https://cloud.githubusercontent.com/assets/1789723/8936215/0a64c572-351f-11e5-9ec4-63c0951837de.png)

**Comment by marcellosachs** [comment]
When I click 'check work', nothing happens, and I get the following error in the console : 
(link https://staging.quill.org/activities/27?session=1680803)
![screen shot 2015-07-28 at 3 35 32 pm](https://cloud.githubusercontent.com/assets/1789723/8941598/7884f8be-353e-11e5-808c-d4a241eb843d.png)

**Comment by wlaurance** [comment]
https://www.quill.org/activities/200?anonymous=true

![screenshot_2015-07-28_15-00-46](https://cloud.githubusercontent.com/assets/1059214/8945098/73256a70-3539-11e5-8c90-cbb9831f9a8d.png)

**Comment by petergault** [comment]
#109 and #118 are likely the same bug with more info.

**Comment by wlaurance** [comment]
Looks like it related to the `-` mark in the question.

I'll look into the parser as to why it errors there.

**Comment by wlaurance** [comment]
This is related to the incorrect mapping of postgres yaml data to the JSON format used by Quill Grammar early this year.

To fix this, we'll need to make changes in https://github.com/empirical-org/grammar-csv-import

**Comment by wlaurance** [comment]
The hyphen error is fixed now. I've distributed the updated content to staging, production, and partner.

@petergault please test this one. https://staging.quill.org/activities/156?session=1680761

**Comment by wlaurance** [comment]
The "my/myself" one seems to be a typo in the syntax. It is "[myself}" instead of "{myself}".
Also needs to be fixed in grammar-csv-import.

**Comment by wlaurance** [comment]
The my self error has been distributed to staging, production, and partner.

@petergault Please test this one http://quillgrammar.firebaseapp.com/play/sw/g/361,354,356,481,358?student=Nxg0W7A-0H8dmeA8dln_eA&passageId=_U0F5m1oIJcTx5TxJJD5Xg

**Comment by wlaurance** [comment]
@elliotmandel Feel free to test as well ;)

**Comment by elliotmandel** [comment]
Check work button works, closing issue.
