### ISSUE TITLE
Methods to prevent in app cheating 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#11]
- When a student presses check answer they must have made the number of corrections equal 
equal to the number of errors in the story minus 3. If they don't they get a message that says keep going.
- They are told to retry 2 times before they get the final answer. It will tell them on the second try how many they are missing. 
- The teacher can see how many check answers or retry attempts the student used. 
- Refreshing the page should not solve the cache. 

The problem right now is that students will press check answer, see all of the correct answers, and then refresh the page and edit it to mark all of the answers correct.

**Comment by wlaurance** [comment]
We can set local session state, but If someone knows how to clear this, then they could.

But I imagine this would be good enough for now.

**Comment by petergault** [comment]
Yep, this works
