### ISSUE TITLE
Connection Timeout Issues

### ISSUE THREAD

**Issue by wlaurance** [empirical-org/Quill-Grammar#112]
We are experiencing timeout issues from within the iframe on Quill Grammar Production.

**Comment by kriskelly** [comment]
This occurs irregularly only on the passage proofreading part of the app.

**Comment by wlaurance** [comment]
![pending-requests](https://cloud.githubusercontent.com/assets/1059214/8945404/f7cf95d2-353b-11e5-98f9-7e7bc8f528d4.png)

**Comment by wlaurance** [comment]
The connection timeout were cause by a non responsive https server located at `https://quill.org`. We are using WWWizer to redirect our naked domain to the `www` subdomain.

To fix this, we updated the API URL to be `https://www.quill.org` instead of `https://quill.org`.

We switch the DNS A record for quill.org to use Zerigo's DNS HTTP Redirect feature, just so the logic is all in the same place.
