### ISSUE TITLE
Set up error monitoring service. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#119]
We should set up an error monitoring service, such as new relic for tracking errors. 

Let's use Segment.com and then funnel things into Atatus.com

**Comment by petergault** [comment]
https://github.com/pkaminski/firebase-on-error may be helpful as well

**Comment by petergault** [comment]
We're using sentry right now, so we may want to continue using this in the future. 
https://getsentry.com/welcome/

This also looks like a good tool for error monitoring:
https://www.atatus.com/

**Comment by ddmck** [comment]
https://github.com/empirical-org/Quill-Grammar/pull/200
