### ISSUE TITLE
Use Rule Number for Rule ID

### ISSUE THREAD

**Issue by wlaurance** [empirical-org/Quill-Grammar#12]
Since we are keeping track of rule numbers, it will be easy to make this the id number used to identify the object in the rules list.

Right now, the current look up function will work, because the id is equal to the rule number. Once more rules are added to the system, this will not be the case and things will break.

**Comment by wlaurance** [comment]
Now that we are using uid's instead of the number, we will need to create and setup an index for uid to rule numbers.

**Comment by wlaurance** [comment]
This is because of #20

**Comment by wlaurance** [comment]
This isn't true. I was confused on which id I was really using. But this issue is still important before we add any new data through the app's form urls.

**Comment by wlaurance** [comment]
If any new rules are created through the /cms route, they will not work.

**Comment by petergault** [comment]
This is no longer an issue, correct? We can use integer IDs for the rules and be ok?

**Comment by wlaurance** [comment]
Yes,

We will move to a pure integer based id and not the firebase uid scheme.
ᐧ
