### ISSUE TITLE
4.1. Link to Quill Grammar admin form from LMS admin console

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Quill-Grammar#126]

**Comment by petergault** [comment]
### This is the top page for the Content Editor. This needs no styling now, and can simply be 2 links that go to Activities and Concepts. This wireframe is included as a reference to the future design. 

![screen shot 2015-08-10 at 1 58 55 pm](https://cloud.githubusercontent.com/assets/3667179/9184105/154ea86a-3f68-11e5-8029-bbfd57be70ef.png)
