### ISSUE TITLE
Review and fix current Quill Grammar activities

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#127]
This doc outlines all of the broken aspects of the current Quill Grammar activities. As soon as we get the content editor finished, we shoudl review and update these issues:
https://docs.google.com/document/d/1H870w2YYdhjrcG2vFKvBxrkUxkZYL6LKQXMnwpxC6xk/edit

**Comment by elliotmandel** [comment]
For all content edits listed -  reviewed, edited, corrected.
