### ISSUE TITLE
Proofreading: when a student finds no errors, no sentence writing exercises get generated

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Quill-Grammar#128]
![screen shot 2015-08-06 at 6 23 17 pm](https://cloud.githubusercontent.com/assets/176935/9126927/66c3868c-3c68-11e5-8f44-d5c25e114cdf.png)

Steps to reproduce:

- Start a proofreading activity.
- Make a bunch of nonsense corrections, do not change any of the correctable parts of the passage.
- Click check work, click through to the generated sentence writing exercises.
- See no exercises.

I used this play session and user ID:

https://grammar.quill.org/play/pf?student=KfxOcyLrYtYbUuC10RqLcw&uid=E0COBlHa6wFi0fiSdmN8bg

**Comment by wlaurance** [comment]
It looks like there are no practice questions for the rule numbers.

https://grammar.quill.org/play/sw/g/43,46,45,42?student=KfxOcyLrYtYbUuC10RqLcw&passageId=E0COBlHa6wFi0fiSdmN8bg

![screenshot_2015-08-06_18-39-21](https://cloud.githubusercontent.com/assets/1059214/9127074/7818517c-3c6a-11e5-9b92-2eefe405a379.png)

This could be an issue with old data.

There is also reason to make it the default case, if 0 questions are generated, then finish and move to the next state (in this case redirecting to the lms).

**Comment by petergault** [comment]
Sure, yeah lets do that as a fall back for now. The issue is that the passage is associated with the wrong rules, we will need to remap them.
