### ISSUE TITLE
Underline Errors in Passages

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#15]
There should be a checkbox in the CMS for the story that states:
[  ] Underline Errors in Passages
The code term here should be “UnderlineErrorsInProofreader”

The idea is that when this box is checked, all of the text that is in curley braces has an underline beneath it. When it is not checked, there is no underline. 

With this system in place we can delete the parentheses, and use a much cleaner interface. This setting will be local to individual students for now.

**Comment by wlaurance** [comment]
So if [text in brackets] and UnderlineErrorsInProofreader is true, then underline?

If [text in brackets] and UnderlineErrorsInProofreader is false, show brackets? Or just no underline?

**Comment by petergault** [comment]
So if [text in brackets] and UnderlineErrorsInProofreader is true, then underline?
Yes

If [text in brackets] and UnderlineErrorsInProofreader is false, show brackets? Or just no underline?
Show no underline.

**Comment by petergault** [comment]
All lines turned off by default. 

![screen shot 2015-02-25 at 6 07 49 pm](https://cloud.githubusercontent.com/assets/3667179/6382852/3e1633ec-bd1a-11e4-8816-5e1924dc69ad.png)
