### ISSUE TITLE
Sections or topic_categories?

### ISSUE THREAD

**Issue by wlaurance** [empirical-org/Quill-Grammar#154]
https://github.com/empirical-org/Quill-Grammar/blob/develop/src/scripts/services/lms/standard_level.js#L8-L14

Should ^^ be topic_categories instead?

**Comment by kriskelly** [comment]
Good question, actually I'm not sure now.

**Comment by wlaurance** [comment]
When trying to mashup the existing v1 data to turn it into v2, none of the sections would line up with what I had.

**Comment by kriskelly** [comment]
Ah ok, I may have gotten topic categories and sections mixed up, let me
double check on that.

**Comment by kriskelly** [comment]
@wlaurance I verified that standard_level = section, at least that's what it says in the notes on this mock:

https://moqups.com/gault8121/J7pltM9L/p:afbd17f3e

**Comment by wlaurance** [comment]
OK thanks.

This isn't an issue for the concept data migration since this model doesn't include these fields.
