### ISSUE TITLE
Rule questions are associate with the wrong concept

### ISSUE THREAD

**Issue by wlaurance** [empirical-org/Quill-Grammar#157]
Problem: 
The rule However exists in three places. 
This is due to the fact that the rule ID was being used. 

The solution is to use the concept_level_0 name as the basis for link the concepts to the the questions. 

The questions have to be deleted and then re-added using the concept_level_0 has the bridge between them. 

What's missing from the spreadsheet is the prompt and the instructions for the questions. How will we associate this to the questions? For example, we could use the question answer to join these two data sets. We have the old data set (all practice questions with instructions and prompt). On the rebuilt practice question set, we can search the old set by answer to retrieve the instructions and prompt.

The data mapping needs to use the new spreadsheet data and sprinkle the old (prompt, instructions, ruleNumber) into the existing list of rule questions.

Game plan for accomplishing this:

1. Pull down updated copy of "Master - Quill Grammar Data Set" csv (Once Elliot and Peter make the appropriate fixes.
2. Iterate through this list of rule questions and group by concept chain.
3. Use the questions text to match against the old rule questions (to pull `prompt` and `instructions`)

This should fix the rule questions by having them appropriately under the correct concepts.

**Comment by petergault** [comment]
Validators
- [ ] Concepts = 213
- [ ] Questions = 1123. 
- [ ] All questions from "Master Rule Set" perfectly match with all questions from the JSON file.

**Comment by elliotmandel** [comment]
Master - Quill Grammar Data Set has been appropriately fixed

**Comment by wlaurance** [comment]
@petergault I think it is the case there are more than 213 concept chains.

It is the case there are 213 Concept Level 0s.

But there are more than 213 combinations of {Concept_2, Concept_1, Concept_0}.

Reworking the data, I get 243 total in Quill Grammar. We can subtract 3 (Those last 3 with the awesome name concept) and we have 240.

It also looks like there are a few errors among them. But given what we've talk about regarding the different ways to end up at a level 0 concept, I think there can, and is, more than 213. Probably not 240, but a little more than 213.

As for practice questions, I end up with 1099.

We should look this over tomorrow.

**Comment by wlaurance** [comment]
A few of the concepts did not match exactly because the quotes in them were double quoted.

`Ending in ""Y""` instead of `Ending in "Y"` for a pseudo example.

This helped a few of the stragglers match up properly.

Now all of the chains are complete mod the 3 "awesome" test practice concepts. I think these can be removed from the data set.

**Comment by wlaurance** [comment]
Slight update for number of concept chains.

I'm using the incorrect function and counting the number of keys. I need to use the array length function on the firebase array object.

When I look at just the array elements, there are 225. So there are 222 real concept chains (-3 from the awesome questions).

**Comment by petergault** [comment]
There are a few instances where the same name is being used in two instances. For example, the concept "it's" belongs in two chains. If this is a problem we can enforce uniqueness by modifying the name. For example: "it's (contractions)"

**Comment by wlaurance** [comment]
No, it isn't an issue because the chain uniquely identifies itself.

**Comment by wlaurance** [comment]
We can think of each concept chain has having a 3 part key where the key is the combination of concept_2 + concept_1 + concept_0
