### ISSUE TITLE
Some practice questions are missing data

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#16]
When you press check answer on this passage and then press go to my lesson you don’t see any data. Can you automatically search the database to see if any practice questions are missing this data? Or maybe write a test where it fails if there is no data? 

https://quillgrammar.firebaseapp.com/play/sw/g/187,187,187,187,187,187,187

![screen shot 2015-02-25 at 11 25 14 am](https://cloud.githubusercontent.com/assets/3667179/6375020/60c938d6-bce2-11e4-8b40-d94c90498e7f.png)

**Comment by wlaurance** [comment]
For this rule in particular, https://quillgrammar.firebaseio.com/cms/rules/187, there are no rule questions associated.

**Comment by wlaurance** [comment]
I can get a list of all of the ruleNumbers that do not have any rule questions

**Comment by wlaurance** [comment]
OK, so now, https://quillgrammarstaging.firebaseapp.com/play/sw/g/187 will work

**Comment by wlaurance** [comment]
https://quillgrammar.firebaseapp.com/play/sw/g/187

Also works.
