### ISSUE TITLE
Capitalize Dates and Names of People Activity Error

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Quill-Grammar#161]
## Problem 

![screen shot 2015-09-18 at 6 33 00 pm](https://cloud.githubusercontent.com/assets/8131465/9972645/9d948b96-5e34-11e5-937f-6545cfce8f17.png)

When you write "Rick runs slower than Lisa" it comes back with "Rick runs slower than {Lisa}." and says the answer is wrong. 

## Solution
- [x] Try to go into the activity editor to fix this problem

I tried to login but got a 500 error.

**Comment by elliotmandel** [comment]
This content was lost during the shift to the new CMS - I will remake it correctly from the Content Editor's side.
