### ISSUE TITLE
"Janet sends a letter (Fiction)" does not recognize correct responses

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Quill-Grammar#162]
https://www.quill.org/activity_sessions/anonymous?activity_id=53

I completed this passage proofreading activity correctly, but the system still though I had made mistakes.
This was reported by a user (and replicated on my machine).
![screen shot 2015-09-22 at 11 40 25 am](https://cloud.githubusercontent.com/assets/1789723/10023274/3f30970a-611f-11e5-9d94-1aac42b11e18.png)
![screen shot 2015-09-22 at 11 40 33 am](https://cloud.githubusercontent.com/assets/1789723/10023276/40fe7534-611f-11e5-9912-99d8079aa32f.png)
![screen shot 2015-09-22 at 11 40 44 am](https://cloud.githubusercontent.com/assets/1789723/10023277/42ce2d28-611f-11e5-988e-8c49380a4b8a.png)
![screen shot 2015-09-22 at 11 40 52 am](https://cloud.githubusercontent.com/assets/1789723/10023278/44da30b2-611f-11e5-88c6-b2dfed03f126.png)

**Comment by wlaurance** [comment]
Thanks @marcellosachs I'll take a look into it.

**Comment by marcellosachs** [comment]
@wlaurance k kewl

**Comment by marcellosachs** [comment]
the user reporting this originally mentioned that it occurred in sentences in the Capitalization 1.2a topic. Specifically, the sentence containing "Magic Johnson was born on August 14th, 1959".

**Comment by elliotmandel** [comment]
Corrected both the Janet passage and the Magic Johnson one. Should both be good to go now.

Janet's problem was an extra space between two of the words. I believe Magic Johnson's was an extra {} for August, which is now removed.
