### ISSUE TITLE
Double Quotations

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#172]
Throughout the app there are instances where a single set of quotation marks was turned into two sets of quotation marks. In all instances where there are `""` should be changed to `"`. This applies to the:
- rule descriptions, 
- titles
- possibly the sentences.

**Comment by petergault** [comment]
![screen shot 2015-10-15 at 12 08 04 am](https://cloud.githubusercontent.com/assets/3667179/10507995/4a4d20d8-72d9-11e5-8ece-03a73af673b6.png)

For example....

**Comment by petergault** [comment]
![screen shot 2015-10-17 at 9 30 18 pm](https://cloud.githubusercontent.com/assets/3667179/10562077/cd08c70e-7516-11e5-916f-f10008c381d6.png)

**Comment by wlaurance** [comment]
The data has been updated in Quill Grammar Staging.
