### ISSUE TITLE
Cannot Update Activities

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#175]
For example, with this activity:
https://quillgrammarstaging.firebaseapp.com/cms/grammarActivities/5v62jVAjZvDIdXjMpDMr3g

By default, neither built or broke are selected. Selecting those activities and pressing save does not lead to the activity being registered. 

After trying a couple of times, it would load this error message:

![screen shot 2015-10-15 at 12 02 33 am](https://cloud.githubusercontent.com/assets/3667179/10506798/6714fea6-72d0-11e5-99f6-efd18d13a9b3.png)

**Comment by wlaurance** [comment]
One unrelated issue, is takes a few seconds for all of the requests to finish and we should block any UI events from processing (only cancel spinner when everything is done loading).
