### ISSUE TITLE
Drop down not showing all the options

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#176]
We have a concept called Spoke. 
You can see it here: 
https://quillgrammarstaging.firebaseapp.com/cms/concepts/-Jzw0qjNNnNInNWZT9tI

It is in Irregular Past Tense Verbs
However, it does not appear as an option when selecting Irregular Past Tense Verbs from the drop down. 

![screen shot 2015-10-14 at 11 55 56 pm](https://cloud.githubusercontent.com/assets/3667179/10506887/171c7b44-72d1-11e5-950c-7db10b4ac56a.png)

# The Test
I should be able it to add it to this activity:
https://quillgrammarstaging.firebaseapp.com/cms/grammarActivities/5PZONjaMfhY9ofF9RTEvBg

**Comment by wlaurance** [comment]
Below are some screen shots showing the problem.

![screenshot_2015-10-15_08-59-27](https://cloud.githubusercontent.com/assets/1059214/10519557/1c070ed6-731b-11e5-8ab3-f5e33ef781e5.png)

The top photo is from the LMS /api/v1/concepts request. As you can see, there are two entries for "Irregular past tense verbs"

One goes to parent_id 52 (Nouns and Pronouns)
![screenshot_2015-10-15_09-06-43](https://cloud.githubusercontent.com/assets/1059214/10519809/2ec03c90-731c-11e5-9436-1b4ed2daad88.png)

And the other goes to 155 (Verbs)
![screenshot_2015-10-15_09-07-15](https://cloud.githubusercontent.com/assets/1059214/10519817/3b20ecb4-731c-11e5-96a8-7b9170c47a42.png)

I believe that the chain ending with Verbs is correct.

In Firebase, we have the correct Level 2, Level 1 LMS data. But the associated Level 0 data is for the Nouns and Pronouns chain.

Therefore, when the system builds the dropdowns and filters, the "Spoke" will only show up under, Nouns + Pronouns, Irregular Past tense verbs, Spoke, like so
![screenshot_2015-10-15_09-10-45](https://cloud.githubusercontent.com/assets/1059214/10519907/b084d8c6-731c-11e5-9aa7-b351cd9188fe.png)

The reason this error happened is during the migration script, the code found the first matching concept and worked it's way up. It found "Spoke" here,
![screenshot_2015-10-15_09-12-45](https://cloud.githubusercontent.com/assets/1059214/10519974/f362b83e-731c-11e5-8d2f-b9222b6f454d.png)
And walked up to 171 (which is Irregular Past Tense Verbs with parent id of nouns and pronouns).

**Comment by wlaurance** [comment]
The concepts Edit/Create isn't fully built out, meaning it doesn't reach out to the LMS for details.

This never happened because for launch we were not adding anymore.


I can see an easy fix we can do under an hour, and I see I longer fix.


The hour(ish) fix:

Fix the concept chains in /api/v1/concepts
Manually fix the Spoke concept in Firebase

The long fix:

Fix the concept chains in /api/v1/concepts
Provide the option to associate a Quill Grammar Concept with a different LMS Concept Level 0

If "Spoke" is the only issue, I'd recommend we do the hour long fix.
Then document this problem for future improvements.

**Comment by wlaurance** [comment]
I just updated the `parent_id` of "Spoke" to be `161` instead of 171. And now it shows up in the dropdown.

**Comment by wlaurance** [comment]
In addition to spoke, @elliotmandel found 3 other errors.

```
"Proper Nouns" not showing up underneath Common & Proper Nouns

"That" not showing up underneath Relative Pronouns

"You're" not showing up underneath Commonly Confused Words
```

**Comment by wlaurance** [comment]
Here are the 3 new concept entries in Quill Grammar Firebase
1. Proper Nouns (Common & Proper Nouns) https://quillgrammar.firebaseio.com/v2/concepts/-Jzw0qjLNEeZAERlRkrq ![screen shot 2015-10-16 at 12 27 57 pm](https://cloud.githubusercontent.com/assets/1059214/10551371/6580b012-7401-11e5-8c45-9e3751f6e389.png)
2. That (Relative Pronouns) https://quillgrammar.firebaseio.com/v2/concepts/-Jzw0qjP5tpJMplbm7kA
![screen shot 2015-10-16 at 12 34 11 pm](https://cloud.githubusercontent.com/assets/1059214/10551543/5bff0b32-7402-11e5-9187-e9d5abab8283.png)
3. You're (Commonly Confused Words) https://quillgrammar.firebaseio.com/v2/concepts/-Jzw0qjQwbyM2twtkmXN 
![screen shot 2015-10-16 at 12 37 45 pm](https://cloud.githubusercontent.com/assets/1059214/10551626/d0ae6ce8-7402-11e5-8bf1-1023f2e54014.png)

Observe the id's of the concept_level_0 parent id's and the rest of the chain. For these 3 (and "Spoke" until I changed it) have the chain linking (id, parent_id) off.

**Comment by wlaurance** [comment]
So why did this happen?

For Proper Nouns there are two `level_0` entries. Each with a unique concept chain.

1. (proper nouns, common and proper, nouns and pronouns) ![screen shot 2015-10-16 at 12 45 47 pm](https://cloud.githubusercontent.com/assets/1059214/10551918/e75aa428-7404-11e5-877c-f838223eed7d.png)![screen shot 2015-10-16 at 12 49 58 pm](https://cloud.githubusercontent.com/assets/1059214/10551907/cda79ad6-7404-11e5-82a9-7e4237561f8e.png)![screen shot 2015-10-16 at 12 53 11 pm](https://cloud.githubusercontent.com/assets/1059214/10551928/f9a72660-7404-11e5-8e3c-828d6c026017.png)

2. (proper nouns, proper nouns, capitalization)
![screen shot 2015-10-16 at 12 55 26 pm](https://cloud.githubusercontent.com/assets/1059214/10551963/5259e694-7405-11e5-9d25-305054e50940.png)![screen shot 2015-10-16 at 12 55 42 pm](https://cloud.githubusercontent.com/assets/1059214/10551962/5259379e-7405-11e5-828c-27a8235f5b89.png)![screen shot 2015-10-16 at 12 55 54 pm](https://cloud.githubusercontent.com/assets/1059214/10551964/525ac726-7405-11e5-8429-ecfe830d2040.png)

@petergault Are both of these chains valid for "Proper Nouns"?

**Comment by wlaurance** [comment]
The same is true for "That", "You're".

How to fix,

1. Fix up Concepts in https://www.quill.org/api/v1/concepts.json
2. Manually Update broken concepts (Proper Nouns, That, You're) in https://quillgrammar.firebaseio.com/v2/concepts

There may be more, and once found they can be fixed using this same process.
