### ISSUE TITLE
Show progress on practice questions

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#18]
Students should see how many questions they have remaining on the practice questions set. For now this can be as simple as showing a number that states: 2/9

Here is a screenshot of what it looks like now (upper right corner, 2/9): 

![screen shot 2015-02-25 at 11 39 11 am](https://cloud.githubusercontent.com/assets/3667179/6375186/6b76c5f4-bce3-11e4-8664-b13e6fdd60ce.png)

**Comment by wlaurance** [comment]
There is a simple 2/9 2/10 on the page now. So it is functionally there.
Didn't put any time into styling or positioning.
