### ISSUE TITLE
Not pulling the name for certain concepts

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#181]
Certain concepts are not showing the name. For example:

![screen shot 2015-10-16 at 5 28 05 pm](https://cloud.githubusercontent.com/assets/3667179/10555887/53fbf9d0-742b-11e5-8d32-c8343b7c2b98.png)
![screen shot 2015-10-16 at 5 05 40 pm](https://cloud.githubusercontent.com/assets/3667179/10555889/589faaae-742b-11e5-9f6b-5a0b7953c39a.png)

The second activity can be played here: https://staging.quill.org/activities/215/retry?classroom_activity_id=40859

The sign in is Student / Student (user / pw).

**Comment by wlaurance** [comment]
Were these the ones with an incorrect rule number?

**Comment by wlaurance** [comment]
This is because there isn't a concept for the rule number

**Comment by ddmck** [comment]
Part of this was due to the rule numbers being a mix of strings & integers in the db.

The issue in the screenshot was due to the the wrong error number being provided.
