### ISSUE TITLE
Results are not being shown at the end of the passage proofreading

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#182]
When you complete a sentence writing activity it shows you the final results for the activity along with the score. 

 However, we are not showing that info on the final results page. This may have not been implemented for the passage proofreading yet, but it'd be great if it could be turned on if it has been.

**Comment by wlaurance** [comment]
Is this inside of Quill Grammar? Or rather the LMS?

From what I can tell, the proofreading activities go to a generated sentence writing activity and then the redirect page same as the normal sentence writer.
