### ISSUE TITLE
Getting stuck on the last page 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#185]
when I complete an activity I'm getting stuck on this last page

![screen shot 2015-10-17 at 10 05 39 am](https://cloud.githubusercontent.com/assets/3667179/10560194/02720c98-74b8-11e5-9c61-78021234131b.png)

**Comment by petergault** [comment]
It seems that this is being caused by the LMS being slow to load the results page, and the default page is a blank question page. 

Is there a chance that once students complete the last activity, we could send them to a page that states: "Loading your results..." with a spinner? This should help deal with the LMS slowness.

**Comment by wlaurance** [comment]
The `503` error from the API has me concerned. That means an error occurred on the LMS. Sounds like QG didn't handle it well.

I'm looking at the stack trace from Slack
<img width="1245" alt="screen shot 2015-10-17 at 11 10 47 am" src="https://cloud.githubusercontent.com/assets/1059214/10561713/f427a4c6-74ea-11e5-961d-f8e17efabce7.png"> about the 503. But checkAnswer null is concerning as well.


Either way, an activity loader spinner sounds like the best UI choice.

**Comment by wlaurance** [comment]
I'm not sure the best way to fix this one. It seems to fail intermittenly

**Comment by wlaurance** [comment]
@petergault the loader is up on staging.
