### ISSUE TITLE
Underline errors in passages 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#186]
The ability to underline errors in passages is not working. Can we fix this? 

For example, the "1. Anansi" activity does not have underlines now, though it is checked in the CMS 

https://www.quill.org/activity_sessions/anonymous?activity_id=203

**Comment by wlaurance** [comment]
@petergault @elliotmandel Please test on staging, https://staging.quill.org/activity_sessions/anonymous?activity_id=203
