### ISSUE TITLE
Either enable html or ignore HTML for descrptions. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#189]
Currently the Quill Grammar app has html embedded within it. How much work would it be to have the LMS read the html information? Alternatively, we can just strip all of the `<br>` and `<i>` tags from the passage and sentence descriptions.

**Comment by wlaurance** [comment]
https://grammar.quill.org/cms/proofreaderActivities/2QZ_aTD1_6PM_uvawpVFjgv

**Comment by petergault** [comment]
The fix is to manually fix
