### ISSUE TITLE
Change Concept Level 0 to Concept Level 1

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#197]
Teachers are complaining about showing the answer. This is because we show the concept level 0. Instead, let's show the concept level 1. This will mask the answer in most cases. 

![show concept level 1](https://cloud.githubusercontent.com/assets/3667179/10649844/41839b5e-7814-11e5-9521-6671756419d6.png)

**Comment by ddmck** [comment]
https://github.com/empirical-org/Quill-Grammar/pull/201
