### ISSUE TITLE
JS Profiling 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#209]
#JS Profiling

I'd recommend to profile the running javascript using Chrome's debugging profiler. 

It is likely that the culprit is a lot of digest cycles on the proofreading activity. (Lower processors cannot do this effectively)

But it could be others things.

http://stackoverflow.com/questions/27750761/efficiency-of-browserify-with-multiple-bundles

**Comment by ddmck** [comment]
Investigating improvements to the Quill Proofreader application.

large number of ng-repeat items in passage
large number of watchers needed
large number of hidden elements for tooltips.

**Comment by ddmck** [comment]
I've reduced the number of watchers by roughly two thirds (before the average passage needed 22000 watchers now it needs 8000, although this may still be too many)

I've started streaming in the passage text, reducing the number of watchers that need to be started simultaneously.

https://github.com/ddmck/Quill-Grammar/commit/bd8fb3092e9e7499dc235c33d5dfca4c7d947da3
