### ISSUE TITLE
Parallel Structure Activity Broken 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#21]
My students are working on the parallel structure exercise, but are experiencing some glitches with what is deemed correct vs. incorrect. It would be great if I could see what they wrote and change the grade if I believe what they wrote is in fact parallel. (One sentence wanted a 'to' in front of each verb and another only wanted the 'to' in front of the first verb. Also one student changed all three verb forms to make it parallel, but it marked it wrong--that's a case where I might want to adjust the score.)

**Comment by elliotmandel** [comment]
Updated the content, confirmed that the questions do represent parallel structure.
