### ISSUE TITLE
Fix Styling on the Concept Overview

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#219]
- Make it square and bigger font.
- Add better spacing. 
- Make it pop up when students get something wrong.

**Comment by ddmck** [comment]
Make it square and bigger font & Add better spacing. Both do-able quickly.

Making it pop when giving an incorrect answer will take a little longer as it will mean moving away from the overview living in a hover state. I can probably use the existing code for the modals.

**Comment by ddmck** [comment]
Concept overviews don't show on mobile devices.

**Comment by ddmck** [comment]
https://github.com/empirical-org/Quill-Grammar/pull/226

**Comment by ddmck** [comment]
I think making the CO pop up when a students gets an answer wrong should be held back until @tomcalabrese and I chat about design. I feel that a slidedown in the header would be less obtrususive, easier to read, be displayable on mobile devices, and easier to programatically display than the current hover state.
