### ISSUE TITLE
Typo in Activity

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#22]
Hello. It turns out that there is an error on the activity Commas After Introductory Prepositional Phrases. The students receive this sentence: My Sister drove us home. Meanwhile, I studied in the back seat.

The system shouldn't have "Sister" capitalized. Just thought you should know. :)

**Comment by RyanNovas** [comment]
We should probably start a milestone for these, they'll all need to be
corrected in one go after we finish the proper migration.

On Tue, Mar 3, 2015 at 2:23 PM, Peter Gault <notifications@github.com>
wrote:

> Hello. It turns out that there is an error on the activity Commas After
> Introductory Prepositional Phrases. The students receive this sentence: My
> Sister drove us home. Meanwhile, I studied in the back seat.
>
> The system shouldn't have "Sister" capitalized. Just thought you should
> know. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Quill-Grammar/issues/22>.
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>

**Comment by wlaurance** [comment]
This one is now fixed from https://github.com/empirical-org/grammar-csv-import/pull/8 which is now live in both staging and production firebase data stores.

**Comment by wlaurance** [comment]
I'm going to close this one now.
