### ISSUE TITLE
Generating a new data set for the questions. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#251]
Problem: I’m stitching together old data sets. One set has the prompts and the other set has the answers, so I need to manually stitch them together. 

A better solution: Pull the entire data set. I need the following columns: Concept Level 1, Question UID, the prompt field of the question, the answer field, and the Common Core standard for the question. 
 
(each question belongs to a rule, and each role has a Common Core standard. This is how you can fetch it.)

- Download the JSON from firebase. I'm not sure how to import it into SQL/excel.

**Comment by RyanNovas** [comment]
I built this parser. https://github.com/empirical-org/grammar-csv-export 

We can easily edit it to pull other fields if ever necessary.
