### ISSUE TITLE
Grammar Errors in Lewis & Clark 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#26]
For @RyanNovas 

Remove errors 1 & 3 on this list, fix 2 . 

# 1
“As they traveled below the country”

This is a weird error because there are many ways you can correct (many different prepositions fit here, such as across). We should strike this because we don’t support the variety. 

# 2
the line “pacific ocean’s coast in present-day Oregon.”
The error is supposed to be On, the correct word is In. It is showing In as the error. 

# 3 
The should / must error is ambiguous in “Both Lewis and Clark thought that must / should return to St. Louis”. I’d remove this.

**Comment by petergault** [comment]
So on reviewing the passage there are two weird phrases that are due to errors in the other passage. The "was keeping a journal" and "were receiving help" are corrected errors from the first passage. 

It's awkward here, and we should just use the past tense: 
change: “ was keeping a journal” to: Lewis kept a journal. Use Kept

In the second linked, “but were receiving help” this is weird. Can you change it to: but received help

**Comment by RyanNovas** [comment]
@petergault in the future can you specify which lessons these occur in

**Comment by RyanNovas** [comment]
First comment is fixed. Waiting for you to finish up reviewing other passages before carrying on. Doesn't matter much for this, but when multiple similar passages are up, we should specify which ones need editing.

**Comment by RyanNovas** [comment]
@petergault do you have further edits, for this or should it be closed?
