### ISSUE TITLE
Rewrite of the Grammar App

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#3]
_From @petergault on December 10, 2014 6:31_

# Part 1: Introduction 

The Quill Grammar (Quill-Lessons) app is composed of two parts:
A sentence writing component and a passage proofreading component. 

**CMS for content**
In the CMS the teacher defines a list of explanations (rules) and a list of practice questions (rule_questions) for each explanation. Each rule is a static block of text. Each rule_question is a prompt and one or multiple answers.

The CMS also stores each passage (story). The story has text that contains errors like {+this-thsi|59} where the negative is what it shown and the positive is what it is compared to. Each number refers to a rule, and the story page contains a legend that details the names for each rule. 

**Sentence Writing**
When the teacher creates a sentence writing activity, the teacher assigns a series of rules and a number of practice questions for each rule. For example, an app might have 2 rules, and each rule has 5 rule_questions, constituting a total of 10 questions. When each question is displayed the app compares the student input against the stored answer. 

**Passage Proofreading**
The passage proofreading app takes the story and breaks each word into a separate text box. The "bugged" words are compared between the correct answer and the student answer. If the student answer does not match the correct answer the word is marked as wrong. For each rule a student gets wrong the site provides 3 practice questions for that rule. Students complete each of the activities. 

# Part 2: Expanded Details for the Quill Grammar App. 
Screenshots + Links

**Rule and questions:** (http://grammar.quill.org/cms/rules)
![screenshot 2014-12-10 at 2 10 05 pm](https://cloud.githubusercontent.com/assets/6655439/5382215/4a3826c0-8076-11e4-84a1-1e82947f4732.png)

**Contents of a Rule:** (http://grammar.quill.org/cms/rules/11/edit)
![screenshot 2014-12-10 at 2 11 25 pm](https://cloud.githubusercontent.com/assets/6655439/5382239/779850c2-8076-11e4-8e84-b40a7a67d8ed.png)

**Passage Proofreading Activity:** (http://www.quill.org/activities/7?anonymous=true)
![screenshot 2014-12-10 at 2 17 35 pm](https://cloud.githubusercontent.com/assets/6655439/5382347/5356b63a-8077-11e4-888b-08ba4c12f23d.png)

**CMS for Passage Proofreading Activity:** (http://www.quill.org/cms/activity_type/story/activities/79/data)
![screenshot 2014-12-10 at 2 01 54 pm](https://cloud.githubusercontent.com/assets/6655439/5382093/3d31f59c-8075-11e4-86e1-35ecd9473877.png)

**Sentence Writing Activity:** (http://www.quill.org/activities/141?anonymous=true)
![screenshot 2014-12-10 at 2 18 44 pm](https://cloud.githubusercontent.com/assets/6655439/5382365/7cfb18a0-8077-11e4-84b2-2faed25b8c81.png)

**CMS for Rule Order in Sentence Writing Activity:**(http://www.quill.org/cms/activity_type/practice_question_set/activities/133/data)
![screenshot 2014-12-10 at 2 04 10 pm](https://cloud.githubusercontent.com/assets/6655439/5382112/79417620-8075-11e4-87ea-79f7c6c96ac4.png)

*Terminology Review*

App_name: Quill Grammar

App_Activity_Name: The name of the activity 

App_Activity_Instance_Id (activity session): The particular activity session of the user. We generate the App_Activity_Instance_Id when the teacher assigns the activity to the student. 

Explanation (Rule):  Each grammar concept has an explanation and a series of grammar_question associated with the concept. 

Practice Question (Rule_Question): Each question for the rule. 

Category: A grouping for the rules to make it easier to search through them.

# Part 3: Generating a Session 

When a teacher assigns an activity to a student it generates an activity session for the student. It is flagged as unstated until the student starts it.  See the student story for a complete look at how the data is passed through the system. 

# Part 4: Disconnect Typing from Sentence Writing

One of the goals is to disconnect the typing from the writing. This means changing the logic for the CMS so that the grammatical term for the sentence writing is placed within a special bracket, and we compare the grammatical term separately from the rest of the sentence. This way if the student gets the answer wrong the answer is still marked correctly. You can see the details here: 

https://github.com/empirical-org/Quill-Lessons/issues/10

# Part 5: Editing Mode

With the editing mode we automatically input the prompt into the answer box. The student edits the prompt rather than re-write it. This helps weak typers. The issue: 

https://github.com/empirical-org/Quill-Lessons/issues/11

Part 6: Settings page for users. 

[This section needs wireframes].
- Teachers set settings
- How settings pass over
- How teachers edit the activities settings. 
- Editing the text mode vs. typing it out. 
- Editing the hints mode in the stories. 
https://github.com/empirical-org/Quill-Lessons/issues/12

_Copied from original issue: empirical-org/Quill-Lessons#22_

**Comment by wlaurance** [comment]
Need to add logic in the cms to not break with a rule with no rule questions
