### ISSUE TITLE
Student Responses are being stripped of spaces

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#308]
A number of student responses are missing spaces after semi-colons or commas. It looks like we may be stripping the space after the comma

For example:
Message: my answer was exactly the same as the one that was right and you counted it wrong

Concept: Introductory Words | However 
Question: We go apple picking in the fall. This year it was too cold. 
Answer: We go apple picking in the fall. {However,} this year it was too cold. 
User Answer: We go apple picking in the fall. However,this year it was too cold.

Message: my answer was exactly the same as the one that was right and you counted it wrong
Concept: Introductory Words | However 
Question: We go apple picking in the fall. This year it was too cold. 
Answer: We go apple picking in the fall. {However,} this year it was too cold. 
User Answer: We go apple picking in the fall. However,this year it was too cold.

Email is provided in the report.

**Comment by ddmck** [comment]
@petergault I don't think this is an issue, just completed the exercise with no issues.
