### ISSUE TITLE
BrainPOP - "Featured Game" art asset.

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#31]
In the center fold there is the top "featured game". We should see if we can take this spot, and we can build an art asset for it to preview with BrainPOP. This is where the current "Build a tree" icon is. https://www.brainpop.com/games/

- We can show the Quill Proofreader animation. This page will need to be white, so we should get Ryan Wilcoxson to re-matte the animation in white. We may also need to reduce the size. 

- Let’s include the following copy. 
- At the top left we state Quill Proofreader with the flag icon. 
- In the middle left we state:  Can you find all of the grammatical errors in these three stories? 
- In the lower left we show a button that states: "Play it now" 

- Let’s include a button that says “Play it now” (even though the whole page its a button). 

- Let's also include something about "Use Snapthought to share your results with your teacher." We can include that + plus a copy of the actual snap thought button under the animation.

**Comment by petergault** [comment]
•	3-4 Screenshots (png; 660x495) 

Want to take these? Probably one of the story with some of the words edited (in bold), one of the feedback page (the words in green / red) and one of the results page. Ryan can take these as well. 



	•	Game Icon (80x80) either w/ transparent background, or square
We should feature the Proofreader Icon - perhaps with both white on transparent and white on green?
 
	•Game Icon (246x246) either w/ transparent background, or square
Same deal.  

	•	Partner Logo - logo(s) to appear with the game in our site.  A transparent or white background is best. Please include two sizes: 246x246 and 150x150.

Include the Quill logo here. 

Optional:
Let’s also create the landing page asset for the site.

**Comment by tomcalabrese** [comment]
@petergault 
All of the BrainPOP assets requested are [here](https://drive.google.com/folderview?id=0B1RagCbDewKWfmVCcUxXZEVocG9mY3dXb0pIMXhwOWxFQWo1djhpdW5ORmloUFgtZUc3Mzg&usp=sharing).

**Comment by petergault** [comment]
Looks great, thanks Tom
