### ISSUE TITLE
Update Copy for BrainPOP

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#32]
1. For the BrainPOP launch, let’s launch Quill Proofreader without the hints. Just the errors, and let’s make sure each of the stories has been proofread by a couple of people. 

In the instructions, let’s include some details along the lines of:
1 - How many errors there are in the story
2 - The lines: “To correct an error, click on it and re-type it”. 
3 - Remove the copy that states they are deleting the words in parentheses.

**Comment by wlaurance** [comment]
This is the correct file if you are <b>editing proofreading activities</b>
https://github.com/empirical-org/grammar-csv-import/blob/master/activities/proofreading_hstore_data.csv

This is the one if you need to edit things for a <b>sentence writing activity</b>
https://github.com/empirical-org/grammar-csv-import/blob/master/activities/activities.csv


My apologies for the mix up. I've ran the script with test changes to confirm the above behavior.

**Comment by RyanNovas** [comment]
Ok. I'll copy edits over.

On Thu, Mar 26, 2015 at 6:39 PM, Will Laurance <notifications@github.com>
wrote:

> This is the correct file if you are *editing proofreading activities*
>
> https://github.com/empirical-org/grammar-csv-import/blob/master/activities/proofreading_hstore_data.csv
>
> This is the one if you need to edit things for a *sentence writing
> activity*
>
> https://github.com/empirical-org/grammar-csv-import/blob/master/activities/activities.csv
>
> My apologies for the mix up. I've ran the script with test changes to
> confirm the above behavior.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Quill-Grammar/issues/32#issuecomment-86743052>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>

**Comment by wlaurance** [comment]
OK, these edits, https://github.com/empirical-org/grammar-csv-import/commit/397b7b5306fda76fe018257fc1204145b677193d,  have been deployed to staging, https://quillgrammarstaging.firebaseapp.com/play/pf?uid=70B-T6vLMTM9zjQ9LCwoCg&brainpop=true

**Comment by wlaurance** [comment]
Next, we need to figure out where to remove the 'remove parentheses text'.

**Comment by RyanNovas** [comment]
I've taken care of the "remove parentheses text" it was in https://github.com/empirical-org/grammar-csv-import/blob/master/activities/proofreading_hstore_data.csv
