### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by wlaurance** [empirical-org/Quill-Grammar#36]
@kriskelly @marcellosachs Do you all have any experience is tracking/analyzing front end javascript apps?

All of my monitoring/logging knowledge pertains to backend code.

Any recommendations?

Any products we are using for core that we can leverage? New Relic perhaps? @petergault  @RyanNovas 

Thanks!

**Comment by wlaurance** [comment]
new relic snippet is up for a new stand alone app, 'Quill Grammar'. It is considered a standalone because it doesn't have an associated APM app.

**Comment by petergault** [comment]
We received a free New Relic account we can hook the app up to. Do we need to swap the api key to be good to go?
