### ISSUE TITLE
New Story from Maggie - 5th Grade CCSS

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#39]
Script and load a single cleaned up version of Maggie's passage.

**Comment by petergault** [comment]
Additional grammar content: https://docs.google.com/document/d/1ybpUrYjbRuU1YKpVWG4ho_q14giurT0-EIwkXwa9tmU/edit

**Comment by elliotmandel** [comment]
Consolidated into 1 issue.
