### ISSUE TITLE
Grammar Errors List

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#42]
Today we found an error in a sentence in the activity called Comma After internal Prepositional Phrases. The error in one of the sentences is "My Sister" where it should be "My sister' because sister is a common noun. It would make it wrong when students corrected that mistake.

**Comment by wlaurance** [comment]
Hey @petergault, Checkout this PR on the Quill Grammar Data. I believe this is what we need to change. https://github.com/empirical-org/grammar-csv-import/pull/8/files

If it is, I'll merge the PR and update the data in firebase.
