### ISSUE TITLE
BrainPOP image update 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#48]
We need to change the copy for the landing page image for BrainPOP. 

- [x] Change the copy of the bottom line to: Use SnapThought(TM) to share your results. (The TM should be the tiny trademark symbol.)
- [x] Email the new image to Katya@brainpop.

**Comment by tomcalabrese** [comment]
@petergault  Katya@brainpop.com was an invalid email address. Do you have the correct one?

**Comment by tomcalabrese** [comment]
Found the correct email.
