### ISSUE TITLE
Activities for Expanded Content / Units 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#50]
Commas and Quotation Marks in Dialogue
3rd Grade CCSS
Comma Usage

To, Too, Two
4th Grade CCSS
Commonly Confused Words

Beginner: Whom, Why
4th Grade CCSS
Nouns & Pronouns

Which, That
4th Grade CCSS
Nouns & Pronouns

Lose, Loose
4th Grade CCSS
Commonly Confused Words

Their, They're, There
4th Grade CCSS
Commonly Confused Words

You're, Your
4th Grade CCSS
Commonly Confused Words

Than, Then
4th Grade CCSS
Commonly Confused Words

Whose, Whom, Who
4th Grade CCSS
Nouns & Pronouns

Colons and Commas in a List
5th Grade CCSS
Comma Usage

Not Only, But Also; Both, And
5th Grade CCSS
Conjunctions

Either, Or; Neither, Nor
5th Grade CCSS
Conjunctions

However, Still
5th Grade CCSS
Comma Usage

Commas for "yes" and "no," tag questions, and addressing people.
5th Grade CCSS
Comma Usage

Commas After Introductory Prepositional Phrases
5th Grade CCSS
Comma Usage

Intensive Pronouns
6th Grade CCSS
Nouns & Pronouns

Recognizing Inappropriate Shifts in Pronoun Number or Gender
6th Grade CCSS
Nouns & Pronouns

Subjective, Objective, and Possessive Pronouns
6th Grade CCSS
Nouns & Pronouns

Misplaced Modifiers
7th Grade CCSS
Structure

Recognize and Correct Inappropriate Shifts in Verb Voice and Mood
8th Grade CCSS
Verbs

Change into Proper Passive or Active Sentences
8th Grade CCSS
Verbs

**Comment by petergault** [comment]
Additional activities:
https://docs.google.com/document/d/1lIr1V4Ti1A4cH0E-6x99j6SNGufInrUCITEUbzZ7loY/edit

**Comment by elliotmandel** [comment]
Combined into 1 issue.
