### ISSUE TITLE
moving from rules to concepts

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Quill-Grammar#63]
If other issues are created for this I can gladly merge in the content from here into a comment on another issue. For now just going to put my thoughts here.

These are the steps that would be required in order to make Quill-Grammar rely on concept relations for generating follow-up questions (instead of relying on rule to rule-question relations)

STEPS

DATA MIGRATION, GRAMMAR_CSV_IMPORT EDITS
1. determine which concept each rule will become
2. create concept records for each former_rule
3. establish parent-child rleations between the fkar_concepts (concepts that were formerly known as rules)
     and the concepts associated to the relevant rule_questions
4. go through each passage and replace each rule_id with the appropriate concept_id (this can be done with a relatively simple script)
5. remove rule_ids from rule_questions.csv
6. change csv-import script so it doesnt create rule objects.
7. change csv-import script so it creates a json object for each concept that is associated to a question. The id of this object will be the id of the concept, and within the object will be the set of questions which correspond to that concept. 
8. also remove concept_tag_name, concept_category_name, and concept_class_name from the files and import script (dont need to be there since we are passing back concept_id) (this is not related to rules-to-concepts transofrmation per-say, but is possible because of the reporting-conceptids feature recently implemented)

QUILL_GRAMMAR EDITS

1. change https://github.com/empirical-org/Quill-Grammar/blob/e0ed120866d4c13ba1354b543c5b069519651a5a/src/scripts/services/rule.js so that instead of retrieving a rule with its rule_question_ids (through an api request to firebase), it retrieves the children concept ids of a given concept (through an api request to the lms), and then for each child concept id thus retrieved, it retreives the json object from firebase that is keyed off the concept_id and contains within it the corresponding set of questions.

**Comment by petergault** [comment]
I'm going to close this issue. Rather than replacing the Rule's system with the Concepts, system, we are instead going to re-map the rule IDs to mirror the concept IDs. This provides us with more flexability (by having a loose connection between the quill grammar content and the concept hierachy), and it is substantially easier from a code perspective, while maintaining coherency from a data perspective. 

To make this magic work, the quill grammar app will need to write new Concept IDs when it creates new rules.
