### ISSUE TITLE
OAuth Integration

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Quill-Grammar#66]
This is a placeholder issue for remaining issues around the OAuth/Firebase integration with the LMS.

- [x] LMS: Protected specific 'sensitive' API endpoints with OAuth ( updating/deleting activity sessions, create/update/delete activities)
- [x] Quill-Grammar: Added a module to help with firebase & Oauth integration. See `feature/oauth-firebase-integration`
- [x] Fix QG OAuth flow to make sure it works when starting an activity from the LMS. One suggestion is to always start the activity from a specific URL rather than the base URL of the app, e.g. quillgrammar.firebase.com/start?activity=whatever and then to modify the OAuth redirect URL so that it points back to that same URL.
- [x] LMS: generated firebase web token uid should be unique per user (right now generating a random UUID every time)
- [x] LMS: Put /api/v1/me controller behind doorkeeper authentication
- [x] LMS: Protect reads on activity sessions /api/v1/activity_sessions#show
- [x] LMS: Set OAuth token expiration to 18 hours
- [x] ~~QG: Fix the 'infinite redirect' bug when the LMS is unavailable to do the OAuth handshake.~~ _(Only happens when LMS and QG are running on same port on dev)_
- [x] ~~QG: Manually expire OAuth / Firebase tokens when finishing the activity~~ (split into #100).
- [x] QG: Ensure that the app still works for anonymous users (skip OAuth and do not try to send data to protected LMS endpoints)
- [ ] ~~LMS/QG: Set up a way to temporarily disable OAuth if there are problems? This one is a question mark because I'm not sure if it's necessary.~~
- [x] Set up QG/LMS integration on staging
  - [x] LMS: Add OAuth application for Quill Grammar staging
  - [x] QG: Add OAuth config vars (client ID, app name, etc.) to staging.config.json
  - [x] Verify that OAuth works end-to-end on staging. Login as a student, finish an activity, verify that it completes successfully and there are no XHR errors at any point.
- [x] Set up QG for production before the deploy

**Comment by marcellosachs** [comment]
I did the "LMS: generated firebase web token uid should be unique per user (right now generating a random UUID every time)" and put it on a branch "oauth-fix-marcello" to make sure its gewd before merging.
