### ISSUE TITLE
Shutdown Old Grammar Ruby on Rails Application

### ISSUE THREAD

**Issue by wlaurance** [empirical-org/Quill-Grammar#71]
Once we have completed #70, we can complete the transition by shutting down
the older Ruby on Rails application.

- [ ] Remove old code base
- [ ] Shutdown Heroku Resources
- [ ] Clean up old DNS resources

**Comment by wlaurance** [comment]
@marcellosachs I'm adding you to this issue if that is OK. We can talk about things, but we are now ready to shut down the old RoR heroku app.

**Comment by marcellosachs** [comment]
I'm going to close this for now as I think we'll probably want to keep the old RoR in standby just in case. After some time with the new QG on prod we can consider deleting the app if it is a drain on resources.
