### ISSUE TITLE
Identify Broken Story and Practice Questions in Production LMS

### ISSUE THREAD

**Issue by wlaurance** [empirical-org/Quill-Grammar#72]
The transition is almost complete.

We can shutdown the old application completely as described in #71 

There are a few activities that are broken and we need to compile a list of the broken ones.

- [x] Someone needs to visit, `https://www.quill.org/cms/activity_type/practice_question_set/activities` and run through all of them to ensure it is correct for the practice questions.
- [x] Someone needs to visit, `https://www.quill.org/cms/activity_type/story/activities` and run through all of the proofreading stories to find any broken ones.

Please comment on this issue with LMS links of all of the ones not working. Not working is defined by the Quill Grammar Application not finding the correct activity (either non-existent or incorrect).

An example of a broken LMS link is, `https://www.quill.org/activities/5?anonymous=true`

It may be the case none are broken. We just need to make sure they all work.

**Comment by petergault** [comment]
To do:
- [ ] Sign in as an admin, review all of the links.
- [ ] For all of the links that are broken, write them down on a list.
- [ ] Set them as "beta" in the LMS.

**Comment by elliotmandel** [comment]
Went through all activities, none else are broken.
