### ISSUE TITLE
Backlog - Re-upload Missing Stories on the LMS

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#73]
We're missing a number of new stories on the new app. We should grab the data and re-upload these stories on the CMS is live.

**Comment by wlaurance** [comment]
So we can do one of two things:

1. Take the existing information from the old grammar app (pg database) and run through the csv uploader process.

2. Wait until CMS is live, and reupload them.

If it is urgent that we get more content up then we can perform 1. If not, just wait for 2.
