### ISSUE TITLE
Lock down terminology for the activities Quill Grammar Provides

### ISSUE THREAD

**Issue by wlaurance** [empirical-org/Quill-Grammar#76]
![screenshot_2015-07-07_17-43-24](https://cloud.githubusercontent.com/assets/1059214/8560712/b31b8940-24cf-11e5-9fd1-5d4d20171972.png)

In the code base we use the terms `sentence` and `proofreading`.

In the LMS we are using the terms `Practice Questions` and `Story`

The mapping is:

LMS | Quill-Grammar Code Base
`Practice Questions` <--> `sentence`

`Story` <--> `proofreading`

I'd like for both sides (LMS | Quill Grammar) to agree on what the terms are.

**Comment by petergault** [comment]
Practice Questions / Sentence should be updated to "Quill Grammar"
Story / Proofreading should be updated to "Quill Proofreader"

In instances where the terms quill grammar and quill proofreader do not make sense, the terms sentence and proofreading should be used. @wlaurance can you work with Marcello to ensure this is the case throughout the LMS?

**Comment by marcellosachs** [comment]
indeed i can work to make this consistent in the LMS. will create an issue on the empirical-grammar repo...

**Comment by marcellosachs** [comment]
It seems that changing names to this effect throughout the QG codebase would be somewhat involved. I think we perhaps are best to wait to do this until after we have launched QG in its most familiar manifestation. Going to move this to a QG v2 milestone. As to changing the names on the LMS codebase, that is represented in issue #782
