### ISSUE TITLE
Teacher Feedback - Update Content: Misc

### ISSUE THREAD

**Issue by elliotmandel** [empirical-org/Quill-Grammar#77]
# Website Edits
- [x] Title lesson needs to be redone- titles should not be in quotes
- [x] Search for emails from Kayla Weis → she pointed out a few content errors
- [x] Search emails from Kris Denue → few students pointed out three errors

# Activity Specific Edits
- [x] In “the militia marches to the tune of yankee doodle” yankee doodle needs a period after it.
- [x]  “the dancer’s move’s” should be “the dancers moves” and then corrected to dancer’s moves
- [x]  in class valedictorian, “valedictorian” should be capitalized
- [x]  “i think its pretty easy” -- its should be it’s
- [x]  “If there are more than ______ than we should run” → should have a comma
- [x]  On “Verb Tense Shift” Activity → First question: Correct: That hat doesn’t fit me because it is too small. Incorrect: That had didn’t fit be because it is too small should be “hat” instead of “had” in the incorrect sentence.

**Comment by RyanNovas** [comment]
Will we be able to redo the title lesson in the new app? Current one doesn't support necessary formatting for titles.

**Comment by elliotmandel** [comment]
All edits confirmed and corrected where appropriate.
