### ISSUE TITLE
4.2. View Activities

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#81]
# 4.2. View Activities

![2 2 _activities 23](https://cloud.githubusercontent.com/assets/3667179/8564676/3e4c0eda-2503-11e5-9ac6-ce46e8bc2111.png)

- [ ] First dropdown: select a standard level (section)
- [ ] Second Dropdown: select the standard (topic)
- [ ] Third Drop down: select the theme. (topic_category). 
- [ ] Display a list of every activity in the system. 
- [ ] Press edit to go to the edit page. 

![4 2 _notes_-_view_activities 4](https://cloud.githubusercontent.com/assets/3667179/9191471/89606a10-3fb6-11e5-8b4d-dfb2d01fcb2d.png)

These are all DB calls, not API calls. 

https://moqups.com/gault8121/J7pltM9L/p:a163c1fc1

**Comment by petergault** [comment]
You can see the current flow here: https://www.quill.org/cms/activity_type/practice_question_set/activities/112/edit

**Comment by marcellosachs** [comment]
@petergault this all looks good. Any of the proposed design strategies is viable. These are my preferences : 

1) To keep the flow separated into two stages, the first stage occuring on the lms and the second stage occuring on the app. This is to maintain the design principle that kris mentioned where each system only knows about the data structures that are stored in its own database (so no system would contain a content form for data that pertained to a different system's database). If there is a page on QG which presents a form where the user can edit content related to data stored on the LMS, then if the structure of data changes on the LMS, QG will have to be updated (as well as any other third-party apps employing this model). It's certainly doable if you think the one-page editor is a necessary UX thing, but in terms of development speed and robustness, I prefer two-pages.

2) I would not use the iframe. Granted, using an i-frame would allow a 1 page UI that didn't require any system to know about another system's data structures (the scenario described above), but I don't think that gain would be worth the loss in technical simplicity. If a 1 page UI was determined to be necessary, I believe I would prefer the drawback of making one system know about another system's data structure to the drawback of using an iframe.

**Comment by petergault** [comment]
These three fields get added to the data: 
![screen shot 2015-08-11 at 12 05 04 am](https://cloud.githubusercontent.com/assets/3667179/9192109/ab9f57fc-3fbc-11e5-8515-2ff4275f620c.png)


# Importaint: Standards are used twice
Each rule is associated with a standard and each activity is associated with a standard.
