### ISSUE TITLE
Not redirecting to LMS or reporting scores on production

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Quill-Grammar#82]
I logged in as student = username: 'test1_c1.s1.s1@cute-iron', password: 's1'
And did the assigned activities : 
Passage Proofreading - "Samir's Baseball Game (Sport)"  
Practice Questions - "At, In, On (Time)"

At the end of both, I was not redirected to the LMS, and scores were not reported to the LMS.

**Comment by marcellosachs** [comment]
teacher for the classroom is : 
email: "t1@gmail.com"
password: "pwd"

**Comment by marcellosachs** [comment]
I'm going to put production LMS into maintenance mode. This problem is also present on staging so perhaps after we work it out on staging, we can move it into production.

**Comment by marcellosachs** [comment]
I redeployed the version of empirical-grammar that would have been live this morning (before todays deploy involving the changing of a link on the homepage and some fixes to get the specs not failing) but the bug seems to persist. Putting prod into maintenance mode for now.

**Comment by marcellosachs** [comment]
Changed prod to point to old Quill Lessons for now, turned maintenance mode off.

**Comment by kriskelly** [comment]
I think this is a real bug. The sentence writing component of the application seems to be integrated with the LMS, but the proofreading portion is not. Likely an oversight by whoever implemented it originally (possibly me). I'm doing some refactoring on the OAuth branch that could make this easier, basically extracting the portion of the app that handles all the LMS integration into what I'm calling the 'finalize' Angular service.

**Comment by marcellosachs** [comment]
Going to split this into two issues
The redirect issue is already covered by kris's issue #86 
Issue concerning the reporting of scores - #95
