### ISSUE TITLE
Proofreading always claims failure for quotation-related questions

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Quill-Grammar#84]
![screen shot 2015-07-13 at 4 32 20 pm](https://cloud.githubusercontent.com/assets/176935/8661868/d670ff7a-2988-11e5-8f4a-c338fdea9774.png)

In the screenshot above, the quotes added by the user are ignored and the answer is marked as incorrect.

I have a suspicion that the app is expecting curly quotes instead of plain double quotes, so the comparison is not working correctly. This can happen if you do something like copy/paste directly from Microsoft Word, which tends to convert plain double quotes to curly.

**Comment by petergault** [comment]
In this instance, t seems that the correct answer is wrong - it has two sets of quotation marks around it. Will, could you fkld;fajdkal;fjdkal; jeioqeioqfj 9w

**Comment by ddmck** [comment]
Searched through the exported DB and couldn't find and instances of this.

Tested the exercise in question and found no errors.
