### ISSUE TITLE
When push new app - Check Capitalization exercise complete button bug

### ISSUE THREAD

**Issue by elliotmandel** [empirical-org/Quill-Grammar#85]
Received a comment from a teacher - when we pushed the new app, there was no option to complete the exercise. After we push the new one back into production, please check.

"When my students complete the Capitalization of Dates and names of people, there is no option to complete. When they refresh the page it makes them start the lesson from the beginning. Any suggestions?"

**Comment by marcellosachs** [comment]
this issue is also recorded in #82 and #86, so going to close this one
