### ISSUE TITLE
App needs a way to return to the LMS student profile after completing an activity

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Quill-Grammar#86]
When you start an activity via the LMS, the activity loads in the iframe. When you complete the activity, you see the results page with a "Back to Menu" link. This takes you to another page of the Quill Grammar app. 

There should be a link, button, or some sort of other UI indicator that the student is done with the activity. Clicking that link should close the iframe and send the student back to their profile page.

**Comment by marcellosachs** [comment]
a issue regarding the same bug was opened on the LMS repo, so I closed that but am pasting @petergault 's comments from that here : 

- Review the process for sending the user from the app to the results page for the new QG app.
- Document the process at quill.readme.io

**Comment by marcellosachs** [comment]
@kriskelly are you currently working on this, or should I take a look?

**Comment by kriskelly** [comment]
I'm not working on it, go for it @marcellosachs.

**Comment by marcellosachs** [comment]
kk @kriskelly

**Comment by marcellosachs** [comment]
@kriskelly @wlaurance looks like this is done...going to close...
