### ISSUE TITLE
BrainPOP App Design

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#9]
Goal: Create a standalone version of Quill Proofreader that features 3 stories from Quill. Students will be able to select one of three stories, and after they finish they will be asked to sign up for Quill. They can also return to the home screen to try another story. We should add some custom doodles into each of these stories to make it fun. 

**Project Overview:**
Our app will be featured here: 
https://www.brainpop.com/search/search.weml?keyword=English%20Games&sections=games

Guideline:
https://docs.google.com/document/d/1_TxF5ML_JcfQHCjtMptfR-xhsWUus4q7RnwBxiv4-0A/edit#heading=h.whq1x8mggbuy

# To do
- [x] Please poke around on GameUP to see how the other apps are designed and structure. 
- [x] Design a landing page that lets users see 3 possible stories. 
- [x] Design the page for each of the passages. We may want to feature custom doodles for some of the passages to make it more fun.
- [x] Once a user presses check answer, we may want to introduce a new round of feedback that says "there are x answers left, keep going."
- [x] Once a user presses check answers, we should then have a message that states what they found and what they missed. Tell them that they can go to Quill.org to save their progress. We should embed the sign up right into the app. We should also include the note that they need to tell their teachers to sign up and create a class so that they can save progress.

# Select Passage Page
![fb8db1da-fbfe-11e3-82ac-5745cd23c261](https://cloud.githubusercontent.com/assets/3667179/6174594/bc805274-b2bd-11e4-8ea4-55d7e1a3a5dd.jpg)

# View Results Page 
 ![3b04f3d8-fc0d-11e3-872f-cf08744aa3b1](https://cloud.githubusercontent.com/assets/3667179/6174591/b6da65bc-b2bd-11e4-9a6d-a25c29082493.jpg)

**Comment by tomcalabrese** [comment]
Mockup:
https://drive.google.com/open?id=0B1RagCbDewKWdFFsRnA0U1o0dW8&authuser=0

Page 1: App landing page. Where a user can access the activities, and see their results.
Page 2: What a Passage Proofreader page looks like. Before a user changes any errors. The story will continue past the fold. (see page 19 for the other story graphics)
Page 3: User revised the passage. The "errors found.." graphic changes with each revision. 
Page 4: A user correctly answered all of the errors. Then they are taken to page 7, where all of their correct revisions will be in green. And on the last correct word, page 11, they will be taken to page 18. They skip the sentence writing.
Page 5: A user answered at least 75% of the errors. Then they are taken to page 7.
Page 6: A user did not answer at least 75% of the errors. They are then asked to go back to page 3.
Page 7: After a user answers at least 75% of the errors, they are then guided through each revision they've made - correct, incorrect, or not necessary. 
Page 8: Showing the "not necessary" result.
Page 9: Showing "incorrect" result.
Page 10: If a user did not get all of the errors completely correct, they are then being taken to page 12 - sentence writing.
Page 11: A user answered all of the errors correctly, and then is being taken to page 18.
Page 12: When a user is introduced to a new concept, the tool tip "concept overview" is displayed. A user can click anywhere to hide the tool tip. And they can hover, or click, over "concept overview" text to display it again. 
Page 13: Shows that it looks like when a user types a sentence. 
Page 14: A user correctly answered the activity.
Page 15: A user answered the activity incorrectly, and is asked to try one more time.
Page 16: A user answered the activity incorrectly twice, and is asked to go to the next activity.
Page 17: After the user answers all of the activities they are taken to the results page. They can then click "go to menu" which takes them to page 18.
Page 18: App landing page with results. 
Page 19: Graphics for different stories, and results. 

Specs:
BrainPOP's iFrame is 800 pixels wide by 600 pixels tall. I've designed all of the pages to fit 800 pixels wide. There will need to be a scroll bar for pages longer than 600 pixels tall.

**Comment by wlaurance** [comment]
Change 75% to 50%

**Comment by wlaurance** [comment]
partnerApp=true showExternalLinks=false|true

**Comment by tomcalabrese** [comment]
https://drive.google.com/folderview?id=0B1RagCbDewKWfndUQ05OdUNvLThNRWNEQUtkTTBHRzNoYUVGSHpaQTFULVRqY2RJYW1zbDA&usp=sharing

Resources for mockups, fonts, colors, and dimensions.  @wlaurance
