### ISSUE TITLE
Getting a weird correction error on a proofreading activity

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Quill-Grammar#92]
![screen shot 2015-07-14 at 5 16 41 pm](https://cloud.githubusercontent.com/assets/176935/8685382/39b5db1e-2a4c-11e5-9dc3-a7645b8fa03f.png)

Looks like it's expecting a UUID for some reason.

**Comment by wlaurance** [comment]
Hmm, that is strange. I've never seen this before. How do we recreate this?

**Comment by kriskelly** [comment]
Try this URL:
https://quillgrammarstaging.firebaseapp.com/play/pf?student=WV7nxruouzvFP0pheUpIIw&uid=mvNABNKNcJfRAVUvaB1yyA

**Comment by wlaurance** [comment]
Here is the firebase entry:

https://quillgrammarstaging.firebaseio.com/activities/passageProofreadings/mvNABNKNcJfRAVUvaB1yyA

**Comment by wlaurance** [comment]
The sentence was wrapped in single quotes. I removed the single quotes from the sentence and things seem to work now.

So to fix it we need to clean up the proofreading activity data. Or make sure the parser can handle single quotes.

The latter will take place over the next couple of weeks.

**Comment by kriskelly** [comment]
Cool, sounds good

**Comment by wlaurance** [comment]
Ok so this error will go away when we move to v2.

I've made the fix permanent in v1 data.
