### ISSUE TITLE
passageResult, passageEntry

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Quill-Grammar#93]
@wlaurance @kriskelly 
It seems that a method is looking for a value in the wrong place. 
Here the value 'type' is set as a direct property of a passageResult object - 
https://github.com/empirical-org/Quill-Grammar/blob/master/src/scripts/app/play/proofreadings/controller.js#L148

But here the property is sought as a property of the passageEntry object, a sub-object of a passageResult : 
https://github.com/empirical-org/Quill-Grammar/blob/master/src/scripts/app/play/proofreadings/controller.js#L480

I think the latter method may have to be edited.

**Comment by kriskelly** [comment]
@marcellosachs @wlaurance I still can't figure out what this means. Does this manifest as a bug somewhere? Is this a code style issue? Do we need to fix this as part of the release?
