### ISSUE TITLE
calculate score for proofreading passage activity

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Quill-Grammar#96]

**Comment by kriskelly** [comment]
@wlaurance @petergault @marcellosachs Marcello already worked on this in this PR: https://github.com/empirical-org/Quill-Grammar/pull/97

I think it's pretty much done at this point, but I could be wrong?

**Comment by marcellosachs** [comment]
@kriskelly it is indeed pretty much wrapped up. I need to refine it according to your suggestions in the PR. Also considering adding a spec with an entrypoint thats earlier in the logic. Going to work on this today because its still fresh in my memory, should be able to finish soon.

**Comment by marcellosachs** [comment]
@wlaurance noted that there might be an issue in the case that a student scores 100% (as in this case, there are no follow-up questions, and there might be logic that occurs at the end of the follow up questions that is still needed)

**Comment by wlaurance** [comment]
This one is good to go!
